- name: forntend configuration 
  hosts: Frontend 
  become: yes 
  tasks:
  - name: disable nginx 
    ansible.builtin.command: dnf module disable nginx -y
  - name: enable nginx 
    ansible.builtin.command: dnf module enable nginx:1.24 -y 

  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx 
      state: present 
  
  - name: enable and start the server 
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes 
    
  - name: Remove a  html dir 
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create html dir 
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
  
  - name: download application   
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
      dest: /tmp/frontend.zip

  - name: extract to the directory 
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes 
  
  - name: Remove a  default contents in nginx 
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy html dir 
    ansible.builtin.copy:
      src: nginx.conf 
      dest: /etc/nginx/nginx.conf