- name: payment server setup 
  become: yes 
  hosts: Payment 
  tasks: 
  - name: maven installation 
    ansible.builtin.command: dnf install python3 gcc python3-devel -y

  - name: adding system user 
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app 
      comment: "roboshop system user"
      shell: /sbin/nologin

  - name: create directory 
    ansible.builtin.file:
      path: /app 
      state: directory 

  - name: download application   
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip 

  - name: extract to the directory 
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app 
      remote_src: yes

  - name: python dependencie installation 
    ansible.builtin.pip:
      name: python 
      executable: pip3.9 
      requirements: requirements.txt 
    args:
      chdir: /app


  - name: copy payment service 
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service 

  - name: systemd demon reloadd 
    ansible.builtin.systemd_service:
      daemon_reload: true
      
  - name: start and enable the server  
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes 

