- name: rabbitmq server connection 
  hosts: Rabbitmq 
  become: yes 
  tasks: 
  - name: copy rabbitmq repo 
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo 

  - name: install rabbitmq  server 
    ansible.builtin.command: dnf install rabbitmq-server -y
  
  - name: start and enable rabbitmq 
    ansible.builtin.service:
      name: rabbitmq-server
      state: started 
      enabled: yes  

  - name: rabbitmq user  setup 
    community.rabbitmq.rabbitmq_user: 
      user: roboshop 
      password: roboshop123 
      permissions: 
        - vhost: / 
          configure_priv: .* 
          read_priv: .* 
          write_priv: .* 
      state: present 
  
  